sudo: required
dist: trusty
group: edge

language: cpp

before_install:
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake --allow-unauthenticated

script:
  - ./build.sh
  - ./build.sh release
